#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#include "wasm_export.h"

/*
 * Adjust these symbol names to match the generated WASM byte array.
 *
 * Example:
 *   extern const unsigned char embedded_wasm[];
 *   extern const unsigned int embedded_wasm_len;
 *
 * If the C array was generated by xxd -i, the symbols may be named like:
 *   hello_wasm[]
 *   hello_wasm_len
 */
extern const unsigned char embedded_wasm[];
extern const unsigned int embedded_wasm_len;

#define WASM_STACK_SIZE (64 * 1024)
#define WASM_HEAP_SIZE  (64 * 1024)
#define WAMR_GLOBAL_HEAP_SIZE (4 * 1024 * 1024)

/*
 * Global heap used by WAMR itself.
 *
 * A fixed memory pool is preferable for enclave execution because the
 * system allocator may rely on OS services that are not available inside
 * the enclave runtime.
 */
static uint8_t wamr_global_heap[WAMR_GLOBAL_HEAP_SIZE] __attribute__((aligned(8)));

int
main(int argc, char **argv)
{
    RuntimeInitArgs init_args;
    wasm_module_t module = NULL;
    wasm_module_inst_t module_inst = NULL;
    char error_buf[128];
    bool ok;
    int ret = 1;

    printf("embedded wasm size = %u bytes\n", embedded_wasm_len);

    memset(&init_args, 0, sizeof(init_args));

    /*
     * Use a fixed memory pool for WAMR.
     *
     * This is more suitable for enclave execution than the system allocator,
     * because the enclave runtime may not provide the same memory management
     * services as a normal Linux process.
     */
    init_args.mem_alloc_type = Alloc_With_Pool;
    init_args.mem_alloc_option.pool.heap_buf = wamr_global_heap;
    init_args.mem_alloc_option.pool.heap_size = sizeof(wamr_global_heap);

    if (!wasm_runtime_full_init(&init_args)) {
        fprintf(stderr, "wasm_runtime_full_init failed\n");
        return 1;
    }

    module = wasm_runtime_load((uint8_t *)embedded_wasm,
                               (uint32_t)embedded_wasm_len,
                               error_buf,
                               sizeof(error_buf));
    if (!module) {
        fprintf(stderr, "wasm_runtime_load failed: %s\n", error_buf);
        goto cleanup_runtime;
    }

    /*
     * Configure WASI arguments before instantiating the module.
     *
     * For a simple WASI program that does not access files,
     * preopened directories, mapped directories, and environment variables
     * can be left empty.
     */
    wasm_runtime_set_wasi_args(module,
                               NULL, 0,      /* preopened directories */
                               NULL, 0,      /* mapped directories */
                               NULL, 0,      /* environment variables */
                               argv, argc);  /* command-line arguments */

    module_inst = wasm_runtime_instantiate(module,
                                           WASM_STACK_SIZE,
                                           WASM_HEAP_SIZE,
                                           error_buf,
                                           sizeof(error_buf));
    if (!module_inst) {
        fprintf(stderr, "wasm_runtime_instantiate failed: %s\n", error_buf);
        goto cleanup_module;
    }

    /*
     * Execute the WASI main entry point.
     */
    ok = wasm_application_execute_main(module_inst, argc, argv);
    if (!ok) {
        const char *exception = wasm_runtime_get_exception(module_inst);
        fprintf(stderr, "wasm execution failed: %s\n",
                exception ? exception : "(no exception)");
        goto cleanup_instance;
    }

    if (wasm_runtime_is_wasi_mode(module_inst)) {
        ret = (int)wasm_runtime_get_wasi_exit_code(module_inst);
    } else {
        ret = 0;
    }

cleanup_instance:
    wasm_runtime_deinstantiate(module_inst);

cleanup_module:
    wasm_runtime_unload(module);

cleanup_runtime:
    wasm_runtime_destroy();

    return ret;
}
